services:
  trader:
    image: zerobha:latest
    container_name: zerobha-trader
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "9880:9880" # Kite OAuth Login Callback
      - "9080:9080" # Web Dashboard & Metrics
    volumes:
      - ./config.local.toml:/app/config.local.toml:ro
      - ./indices.csv:/app/indices.csv:ro
      - ./logs:/app/logs
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
