package models

import "github.com/shopspring/decimal"

// SignalType represents the intent (BuySignal/Sell).
type SignalType int

const (
	BuySignal SignalType = iota
	SellSignal
)

func (s SignalType) String() string {
	switch s {
	case BuySignal:
		return "BUY"
	case SellSignal:
		return "SELL"
	default:
		return "UNKNOWN"
	}
}

// Signal represents a trading decision generated by a strategy.
type Signal struct {
	Symbol   string          `json:"symbol"`
	Type     SignalType      `json:"type"`
	Price    decimal.Decimal `json:"price"` // The trigger price
	StopLoss decimal.Decimal `json:"stop_loss"`
	Target   decimal.Decimal `json:"target"`
	// ProductType: "MIS" (Intraday) or "CNC" (Delivery)
	ProductType string `json:"product_type"`

	// Metadata allows strategies to attach context (e.g., "RSI_Overbought")
	// useful for the Risk Manager and Logs.
	Metadata map[string]string `json:"metadata"`
}
